export interface SmartLeadContact {
  name: string;
  title: string;
  email: string;
  phone: string;
  verified: boolean;
  avatarColor: string;
  linkedin?: string;
}

export interface SmartLeadActivity {
  id: string;
  type: "email" | "meeting" | "signal" | "visit" | "call" | "note";
  title: string;
  time: string;
  channel: string;
  author: string;
  status: string;
  description: string;
  badgeColor: string;
}

export type ProspectTier = "high" | "middle" | "low";

export interface SmartLead {
  id: string;
  businessId: string;
  company: string;
  industry: string;
  location: string;
  country: string;
  employees: string;
  website: string;
  revenue: string;
  fitScore: number;
  tier: ProspectTier;
  intentLevel: "Very High" | "High" | "Medium" | "Low";
  intentTrigger: string;
  whyNow: string;
  primaryContact: SmartLeadContact;
  techStack: string[];
  matchedPresets: string[];
  status: "New Match" | "In Cadence" | "Meeting Booked" | "Engaged" | "Uncontacted";
  lastActive: string;
  activities: SmartLeadActivity[];
}

export interface BusinessProspectAnalytics {
  totalProspects: number;
  highTierCount: number;
  middleTierCount: number;
  lowTierCount: number;
  highTierPercent: number;
  middleTierPercent: number;
  lowTierPercent: number;
  avgFitScore: number;
  buyingSignalsCount: number;
  meetingsBooked: number;
  verifiedContactRate: number;
  signalBreakdown: {
    hiring: number;
    funding: number;
    expansion: number;
    tenders: number;
  };
}

export interface VelocityDayPoint {
  day: string;
  dayLabel: string;
  touches: number;
  opens: number;
  replies: number;
  meetings: number;
}

export function getBusinessVelocityData(businessId: string): VelocityDayPoint[] {
  // 14-day deterministic realistic outreach touches curve
  const days = [
    "Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7",
    "Day 8", "Day 9", "Day 10", "Day 11", "Day 12", "Day 13", "Today"
  ];
  const labels = [
    "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun",
    "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Today"
  ];

  // Base seeds for variety across businesses
  const seedMultiplier = businessId === "nord-tech" ? 1.2 : businessId === "alpine" ? 0.95 : 1.05;
  const touchBases = [22, 38, 45, 41, 35, 12, 9, 28, 48, 52, 44, 39, 15, 34];

  return days.map((day, i) => {
    const touches = Math.round(touchBases[i] * seedMultiplier);
    const opens = Math.round(touches * (0.68 + (i % 3) * 0.05));
    const replies = Math.max(1, Math.round(opens * (0.22 + (i % 2) * 0.04)));
    const meetings = i % 3 === 0 ? Math.max(1, Math.round(replies * 0.35)) : 0;
    return {
      day,
      dayLabel: labels[i],
      touches,
      opens,
      replies,
      meetings,
    };
  });
}

export interface OnboardedBusiness {
  id: string;
  name: string;
  company: string;
  industry: string;
  country: string;
  website: string;
  owner: string;
  created: string;
  avatarColor: string;
  emailsSent: number;
  analytics: BusinessProspectAnalytics;
  prospects: SmartLead[];
}

export const ONBOARDED_BUSINESSES_DATA: OnboardedBusiness[] = [
  {
    id: "nord-tech",
    name: "NordTech Solutions GmbH",
    company: "Nord Tech",
    industry: "Industrial Equipment",
    country: "Germany",
    website: "nordtech-solutions.com",
    owner: "Michael Weber",
    created: "June 14, 2026",
    avatarColor: "#c9ae4d",
    emailsSent: 50000,
    analytics: {
      totalProspects: 148,
      highTierCount: 68,
      middleTierCount: 54,
      lowTierCount: 26,
      highTierPercent: 46,
      middleTierPercent: 36,
      lowTierPercent: 18,
      avgFitScore: 88,
      buyingSignalsCount: 112,
      meetingsBooked: 24,
      verifiedContactRate: 98.6,
      signalBreakdown: {
        hiring: 52,
        funding: 28,
        expansion: 38,
        tenders: 30,
      },
    },
    prospects: [
      {
        id: "prospect-nt-1",
        businessId: "nord-tech",
        company: "Kaiser Precision Automation SE",
        industry: "Industrial Automation",
        location: "Frankfurt, Germany",
        country: "Germany",
        employees: "250–500",
        website: "kaiser-automation.de",
        revenue: "$35M–$50M",
        fitScore: 96,
        tier: "high",
        intentLevel: "Very High",
        intentTrigger: "Active Hiring: 4 Supply Chain & Procurement Leads",
        whyNow: "Expanded factory footprint in Stuttgart last week; actively procuring automated assembly pipeline equipment.",
        primaryContact: {
          name: "Thomas Becker",
          title: "VP Supply Chain & Operations",
          email: "t.becker@kaiser-automation.de",
          phone: "+49 69 4029 182",
          verified: true,
          avatarColor: "#2ae9c9",
        },
        techStack: ["SAP S/4HANA", "Salesforce", "Siemens PLM"],
        matchedPresets: ["all", "high-intent", "hiring"],
        status: "Engaged",
        lastActive: "Today at 14:28",
        activities: [
          {
            id: "act-1",
            type: "email",
            title: "Executive Intro Email Opened (3x)",
            time: "Today at 14:28",
            channel: "Email",
            author: "Automated Cadence",
            status: "Opened",
            description: "Prospect opened intro email 3 times and clicked through to the industrial robotics technical specs deck.",
            badgeColor: "#0284c7",
          },
          {
            id: "act-2",
            type: "signal",
            title: "Procurement Hiring Surge Detected",
            time: "Yesterday at 09:15",
            channel: "Intelligence Signal",
            author: "Smart Engine AI",
            status: "Signal Logged",
            description: "Detected 4 new open senior procurement roles in Stuttgart plant expansion.",
            badgeColor: "#c974f4",
          },
          {
            id: "act-3",
            type: "visit",
            title: "Website Product Matrix Visit",
            time: "3 days ago",
            channel: "Web Analytics",
            author: "Visitor IP: Kaiser Automation",
            status: "Tracked",
            description: "Multiple sessions reviewing automated CNC tooling compatibilities.",
            badgeColor: "#2ae9c9",
          },
        ],
      },
      {
        id: "prospect-nt-2",
        businessId: "nord-tech",
        company: "Lumina Optics AG",
        industry: "Precision Manufacturing",
        location: "Zurich, Switzerland",
        country: "Switzerland",
        employees: "180–300",
        website: "lumina-optics.ch",
        revenue: "$20M–$35M",
        fitScore: 94,
        tier: "high",
        intentLevel: "Very High",
        intentTrigger: "Closed €22M Series B Growth Round (14d ago)",
        whyNow: "Deploying newly raised capital into European sales acceleration and high-throughput optical testing lines.",
        primaryContact: {
          name: "Clara Vogel",
          title: "Director of Strategic Procurement",
          email: "c.vogel@lumina-optics.ch",
          phone: "+41 44 820 4910",
          verified: true,
          avatarColor: "#c974f4",
        },
        techStack: ["HubSpot Enterprise", "Oracle NetSuite", "AWS"],
        matchedPresets: ["all", "high-intent", "funding"],
        status: "In Cadence",
        lastActive: "Yesterday at 16:40",
        activities: [
          {
            id: "act-4",
            type: "email",
            title: "Follow-up Cadence #2 Delivered",
            time: "Yesterday at 16:40",
            channel: "Email",
            author: "Michael Weber",
            status: "Delivered",
            description: "Follow-up email detailing customized optical calibrator pilot proposal sent to Clara Vogel.",
            badgeColor: "#059669",
          },
          {
            id: "act-5",
            type: "signal",
            title: "€22M Growth Round Filing",
            time: "14 days ago",
            channel: "Venture Intelligence",
            author: "Smart Engine AI",
            status: "Verified",
            description: "Series B growth capital earmarked for optical testing hardware upgrades.",
            badgeColor: "#d97706",
          },
        ],
      },
      {
        id: "prospect-nt-3",
        businessId: "nord-tech",
        company: "Helios Clean Energy Systems GmbH",
        industry: "Renewable Energy",
        location: "Munich, Germany",
        country: "Germany",
        employees: "400–750",
        website: "helios-energy.com",
        revenue: "$60M–$90M",
        fitScore: 92,
        tier: "high",
        intentLevel: "High",
        intentTrigger: "Opened New Regional Office in Vienna",
        whyNow: "Entering Austrian and Central European industrial grid markets; scaling vendor pipeline and account outreach.",
        primaryContact: {
          name: "Stefan Lindner",
          title: "Head of Commercial Partnerships",
          email: "s.lindner@helios-energy.com",
          phone: "+49 89 5192 384",
          verified: true,
          avatarColor: "#dc9c56",
        },
        techStack: ["Microsoft Dynamics 365", "Azure", "Marketo"],
        matchedPresets: ["all", "high-intent", "expansion"],
        status: "Meeting Booked",
        lastActive: "Today at 11:00",
        activities: [
          {
            id: "act-6",
            type: "meeting",
            title: "Technical Discovery Sync Scheduled",
            time: "Today at 11:00",
            channel: "Calendar",
            author: "Stefan Lindner",
            status: "Confirmed",
            description: "Meeting scheduled for Thursday at 15:00 CET with engineering team.",
            badgeColor: "#7c3aed",
          },
          {
            id: "act-7",
            type: "email",
            title: "Calendar Invite Accepted",
            time: "Today at 10:45",
            channel: "Email",
            author: "Stefan Lindner",
            status: "Accepted",
            description: "Stefan accepted the invitation for commercial synergy evaluation.",
            badgeColor: "#0284c7",
          },
        ],
      },
      {
        id: "prospect-nt-4",
        businessId: "nord-tech",
        company: "Orbit Cyber Defense Ltd",
        industry: "Enterprise Cybersecurity",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        employees: "120–200",
        website: "orbitdefense.io",
        revenue: "$15M–$25M",
        fitScore: 85,
        tier: "middle",
        intentLevel: "High",
        intentTrigger: "Hiring 6 Enterprise SDRs & Account Executives",
        whyNow: "Ramping up EMEA outbound campaigns to target mid-market banking and healthcare providers.",
        primaryContact: {
          name: "Sanne De Jong",
          title: "VP of Global Revenue",
          email: "s.dejong@orbitdefense.io",
          phone: "+31 20 894 1022",
          verified: true,
          avatarColor: "#42a8a1",
        },
        techStack: ["Salesforce CRM", "Apollo.io", "Gong"],
        matchedPresets: ["all", "hiring"],
        status: "In Cadence",
        lastActive: "2 days ago",
        activities: [
          {
            id: "act-8",
            type: "email",
            title: "Outreach Step #1 Sent",
            time: "2 days ago",
            channel: "Email",
            author: "Michael Weber",
            status: "Sent",
            description: "Initial value proposition email sent regarding automated threat intelligence workflows.",
            badgeColor: "#0284c7",
          },
        ],
      },
      {
        id: "prospect-nt-5",
        businessId: "nord-tech",
        company: "Bavaria Heavy Logistics SE",
        industry: "Logistics & Transport",
        location: "Nuremberg, Germany",
        country: "Germany",
        employees: "600–1,200",
        website: "bavaria-logistics.de",
        revenue: "$110M–$150M",
        fitScore: 82,
        tier: "middle",
        intentLevel: "High",
        intentTrigger: "New Fleet Modernization Tender Published",
        whyNow: "Published public RFP for warehouse telemetry and route optimization vendor contracts.",
        primaryContact: {
          name: "Markus Eichmann",
          title: "Director of Fleet Procurement",
          email: "m.eichmann@bavaria-logistics.de",
          phone: "+49 911 391 842",
          verified: true,
          avatarColor: "#c9ae4d",
        },
        techStack: ["SAP Transportation", "Salesforce", "Tableau"],
        matchedPresets: ["all", "tenders"],
        status: "New Match",
        lastActive: "3 days ago",
        activities: [
          {
            id: "act-9",
            type: "signal",
            title: "Public Tender Announcement Detected",
            time: "3 days ago",
            channel: "Public RFP Portal",
            author: "Smart Engine AI",
            status: "Detected",
            description: "RFP-2026-LOG-772 surfaced by automated scraper matching equipment specs.",
            badgeColor: "#d97706",
          },
        ],
      },
      {
        id: "prospect-nt-6",
        businessId: "nord-tech",
        company: "Vanguard Robotics Corp",
        industry: "Robotics & AI",
        location: "Berlin, Germany",
        country: "Germany",
        employees: "80–150",
        website: "vanguard-robotics.eu",
        revenue: "$12M–$20M",
        fitScore: 78,
        tier: "middle",
        intentLevel: "Medium",
        intentTrigger: "Series A Financing Announced ($14M)",
        whyNow: "Commercializing autonomous mobile warehouse robots for pharmaceutical and electronics manufacturers.",
        primaryContact: {
          name: "Elena Rostova",
          title: "Co-Founder & Chief Product Officer",
          email: "e.rostova@vanguard-robotics.eu",
          phone: "+49 30 7820 449",
          verified: true,
          avatarColor: "#a842a2",
        },
        techStack: ["HubSpot", "Google Workspace", "Segment"],
        matchedPresets: ["all", "funding"],
        status: "New Match",
        lastActive: "4 days ago",
        activities: [
          {
            id: "act-10",
            type: "signal",
            title: "Series A Funding Round Closed",
            time: "4 days ago",
            channel: "Press Release",
            author: "Smart Engine AI",
            status: "Logged",
            description: "Funding announcement identified for AMR production scaling.",
            badgeColor: "#c974f4",
          },
        ],
      },
      {
        id: "prospect-nt-7",
        businessId: "nord-tech",
        company: "Rheinland Precision Castings KG",
        industry: "Industrial Equipment",
        location: "Cologne, Germany",
        country: "Germany",
        employees: "300–450",
        website: "rheinland-castings.de",
        revenue: "$40M–$65M",
        fitScore: 68,
        tier: "low",
        intentLevel: "Low",
        intentTrigger: "Legacy CNC Machine Overhauls Scheduled for Q4",
        whyNow: "Preparing for annual maintenance cycle; potential interest in digital condition monitoring sensors.",
        primaryContact: {
          name: "Jürgen Krause",
          title: "Senior Plant Manager",
          email: "j.krause@rheinland-castings.de",
          phone: "+49 221 884 102",
          verified: false,
          avatarColor: "#64748b",
        },
        techStack: ["Legacy Siemens CNC", "Infor ERP"],
        matchedPresets: ["all"],
        status: "Uncontacted",
        lastActive: "1 week ago",
        activities: [
          {
            id: "act-11",
            type: "signal",
            title: "Standard Maintenance Window Logged",
            time: "1 week ago",
            channel: "Industry Registry",
            author: "Smart Engine AI",
            status: "Low Priority",
            description: "No immediate buying surge identified; recommended for low-intensity nurture sequence.",
            badgeColor: "#64748b",
          },
        ],
      },
      {
        id: "prospect-nt-8",
        businessId: "nord-tech",
        company: "Stuttgart Tool & Die Works",
        industry: "Manufacturing",
        location: "Stuttgart, Germany",
        country: "Germany",
        employees: "90–140",
        website: "stuttgart-tooldie.de",
        revenue: "$8M–$14M",
        fitScore: 62,
        tier: "low",
        intentLevel: "Low",
        intentTrigger: "General Inbound Newsletter Subscription",
        whyNow: "Staff member subscribed to technical whitepapers; no direct budget authorization established yet.",
        primaryContact: {
          name: "Anke Meyer",
          title: "Tooling Technician",
          email: "a.meyer@stuttgart-tooldie.de",
          phone: "+49 711 409 231",
          verified: true,
          avatarColor: "#475569",
        },
        techStack: ["Autodesk Inventor", "SolidWorks"],
        matchedPresets: ["all"],
        status: "Uncontacted",
        lastActive: "2 weeks ago",
        activities: [
          {
            id: "act-12",
            type: "visit",
            title: "Whitepaper Download",
            time: "2 weeks ago",
            channel: "Marketing Portal",
            author: "Anke Meyer",
            status: "Downloaded",
            description: "Downloaded 'Predictive Maintenance in Heavy Tooling' PDF.",
            badgeColor: "#64748b",
          },
        ],
      },
    ],
  },
  {
    id: "alpine",
    name: "NordTech Solutions GmbH (Alpine Division)",
    company: "Alpine Solutions",
    industry: "Industrial Equipment",
    country: "Germany",
    website: "alpine-solutions.eu",
    owner: "Michael Weber",
    created: "June 14, 2026",
    avatarColor: "#42a8a1",
    emailsSent: 32000,
    analytics: {
      totalProspects: 94,
      highTierCount: 42,
      middleTierCount: 36,
      lowTierCount: 16,
      highTierPercent: 45,
      middleTierPercent: 38,
      lowTierPercent: 17,
      avgFitScore: 86,
      buyingSignalsCount: 76,
      meetingsBooked: 18,
      verifiedContactRate: 97.4,
      signalBreakdown: {
        hiring: 34,
        funding: 18,
        expansion: 26,
        tenders: 16,
      },
    },
    prospects: [
      {
        id: "prospect-alp-1",
        businessId: "alpine",
        company: "Helvetic Micro-Systems AG",
        industry: "Precision Manufacturing",
        location: "Basel, Switzerland",
        country: "Switzerland",
        employees: "140–220",
        website: "helvetic-micro.ch",
        revenue: "$18M–$28M",
        fitScore: 95,
        tier: "high",
        intentLevel: "Very High",
        intentTrigger: "Opening New Cleanroom Production Facility",
        whyNow: "Investing CHF 15M in automated cleanroom test stations with Q3 delivery requirements.",
        primaryContact: {
          name: "Beatrix Steiner",
          title: "VP of Quality & Automation",
          email: "b.steiner@helvetic-micro.ch",
          phone: "+41 61 729 440",
          verified: true,
          avatarColor: "#2ae9c9",
        },
        techStack: ["Siemens TIA Portal", "SAP", "LabVIEW"],
        matchedPresets: ["all", "high-intent", "expansion"],
        status: "Engaged",
        lastActive: "Today at 09:30",
        activities: [
          {
            id: "alp-act-1",
            type: "email",
            title: "Proposal Review Acknowledged",
            time: "Today at 09:30",
            channel: "Email",
            author: "Beatrix Steiner",
            status: "Replied",
            description: "Beatrix replied: 'Specifications look aligned with our cleanroom standards. Let's schedule a vendor sync.'",
            badgeColor: "#059669",
          },
          {
            id: "alp-act-2",
            type: "signal",
            title: "Cleanroom Facility Expansion Announced",
            time: "5 days ago",
            channel: "Swiss Commercial Gazette",
            author: "Smart Engine AI",
            status: "Verified",
            description: "CHF 15M cleanroom investment confirmed in Basel Canton registry.",
            badgeColor: "#c974f4",
          },
        ],
      },
      {
        id: "prospect-alp-2",
        businessId: "alpine",
        company: "Tyrol Sensor Engineering GmbH",
        industry: "Industrial Automation",
        location: "Innsbruck, Austria",
        country: "Austria",
        employees: "95–160",
        website: "tyrol-sensors.at",
        revenue: "$14M–$22M",
        fitScore: 91,
        tier: "high",
        intentLevel: "High",
        intentTrigger: "Recruiting Lead Embedded Firmware Architect",
        whyNow: "Accelerating integration of wireless telemetry modules onto alpine pipeline monitoring units.",
        primaryContact: {
          name: "Florian Hofer",
          title: "Chief Technology Officer",
          email: "f.hofer@tyrol-sensors.at",
          phone: "+43 512 809 112",
          verified: true,
          avatarColor: "#c974f4",
        },
        techStack: ["Altium", "Embedded C++", "AWS IoT"],
        matchedPresets: ["all", "high-intent", "hiring"],
        status: "In Cadence",
        lastActive: "Yesterday at 15:10",
        activities: [
          {
            id: "alp-act-3",
            type: "email",
            title: "Intro Sequence Delivered",
            time: "Yesterday at 15:10",
            channel: "Email",
            author: "Michael Weber",
            status: "Delivered",
            description: "Customized technical case study delivered regarding wireless industrial gateways.",
            badgeColor: "#0284c7",
          },
        ],
      },
      {
        id: "prospect-alp-3",
        businessId: "alpine",
        company: "Salzburg Alpine Dynamics",
        industry: "Industrial Equipment",
        location: "Salzburg, Austria",
        country: "Austria",
        employees: "70–110",
        website: "salzburg-dynamics.at",
        revenue: "$9M–$15M",
        fitScore: 76,
        tier: "middle",
        intentLevel: "Medium",
        intentTrigger: "Annual Equipment Replacement Review",
        whyNow: "Reviewing vendor agreements for precision testing rigs before year-end budget lock.",
        primaryContact: {
          name: "Matthias Wallner",
          title: "Purchasing Lead",
          email: "m.wallner@salzburg-dynamics.at",
          phone: "+43 662 550 918",
          verified: true,
          avatarColor: "#dc9c56",
        },
        techStack: ["Microsoft 365", "Dynamics NAV"],
        matchedPresets: ["all"],
        status: "New Match",
        lastActive: "3 days ago",
        activities: [
          {
            id: "alp-act-4",
            type: "signal",
            title: "Vendor Review Notice Published",
            time: "3 days ago",
            channel: "Procurement Bulletin",
            author: "Smart Engine AI",
            status: "Logged",
            description: "Identified upcoming procurement cycle for testing rigs.",
            badgeColor: "#d97706",
          },
        ],
      },
      {
        id: "prospect-alp-4",
        businessId: "alpine",
        company: "Bregenz Metalcraft GmbH",
        industry: "Manufacturing",
        location: "Bregenz, Austria",
        country: "Austria",
        employees: "45–80",
        website: "bregenz-metalcraft.at",
        revenue: "$5M–$8M",
        fitScore: 64,
        tier: "low",
        intentLevel: "Low",
        intentTrigger: "Local Trade Fair Attendance Registered",
        whyNow: "Registered as attendee for Salzburg Industrial Trade Fair; early discovery phase.",
        primaryContact: {
          name: "Lukas Schuler",
          title: "Workshop Supervisor",
          email: "l.schuler@bregenz-metalcraft.at",
          phone: "+43 5574 311 02",
          verified: false,
          avatarColor: "#64748b",
        },
        techStack: ["Manual Mills", "Basic CAD"],
        matchedPresets: ["all"],
        status: "Uncontacted",
        lastActive: "10 days ago",
        activities: [
          {
            id: "alp-act-5",
            type: "signal",
            title: "Trade Fair Attendee List Match",
            time: "10 days ago",
            channel: "Expo Registry",
            author: "Smart Engine AI",
            status: "Low Priority",
            description: "Attendee badge logged. Low fit score due to manual equipment baseline.",
            badgeColor: "#64748b",
          },
        ],
      },
    ],
  },
  {
    id: "biz-5",
    name: "Novus Medical Instruments",
    company: "Novus Medical Instruments",
    industry: "Enterprise Software",
    country: "Sweden",
    website: "novus-medical-instruments.com",
    owner: "Sarah Jenkins",
    created: "November 16, 2026",
    avatarColor: "#c974f4",
    emailsSent: 27285,
    analytics: {
      totalProspects: 112,
      highTierCount: 52,
      middleTierCount: 42,
      lowTierCount: 18,
      highTierPercent: 46,
      middleTierPercent: 38,
      lowTierPercent: 16,
      avgFitScore: 89,
      buyingSignalsCount: 88,
      meetingsBooked: 22,
      verifiedContactRate: 99.1,
      signalBreakdown: {
        hiring: 42,
        funding: 24,
        expansion: 28,
        tenders: 18,
      },
    },
    prospects: [
      {
        id: "prospect-nov-1",
        businessId: "biz-5",
        company: "Nordic Diagnostics BioTech AB",
        industry: "MedTech & Diagnostics",
        location: "Stockholm, Sweden",
        country: "Sweden",
        employees: "210–350",
        website: "nordic-diagnostics.se",
        revenue: "$30M–$45M",
        fitScore: 97,
        tier: "high",
        intentLevel: "Very High",
        intentTrigger: "CE-IVDR Regulatory Approval Granted for Rapid Assay",
        whyNow: "Scaling production rollout across 12 EU member states; procuring automated compliance telemetry platform.",
        primaryContact: {
          name: "Astrid Lindholm",
          title: "Chief Regulatory & Commercial Officer",
          email: "a.lindholm@nordic-diagnostics.se",
          phone: "+46 8 409 2210",
          verified: true,
          avatarColor: "#c974f4",
        },
        techStack: ["Veeva Vault", "Salesforce Health Cloud", "SAP"],
        matchedPresets: ["all", "high-intent", "expansion"],
        status: "Meeting Booked",
        lastActive: "Today at 13:15",
        activities: [
          {
            id: "nov-act-1",
            type: "meeting",
            title: "Product Demo & Architecture Call",
            time: "Today at 13:15",
            channel: "Google Meet",
            author: "Sarah Jenkins",
            status: "Completed",
            description: "Demonstrated automated IVDR compliance audit log generator. Next step: Security review.",
            badgeColor: "#7c3aed",
          },
          {
            id: "nov-act-2",
            type: "signal",
            title: "EU IVDR Approval Published",
            time: "3 days ago",
            channel: "EU Notified Body Registry",
            author: "Smart Engine AI",
            status: "Verified",
            description: "Regulatory clearance triggers mandatory compliance reporting tooling rollout.",
            badgeColor: "#059669",
          },
        ],
      },
      {
        id: "prospect-nov-2",
        businessId: "biz-5",
        company: "Kobenhavn Biosystems ApS",
        industry: "Life Sciences",
        location: "Copenhagen, Denmark",
        country: "Denmark",
        employees: "130–190",
        website: "kbh-biosystems.dk",
        revenue: "$16M–$24M",
        fitScore: 92,
        tier: "high",
        intentLevel: "High",
        intentTrigger: "Hiring 5 Clinical Data Integration Engineers",
        whyNow: "Integrating digital EHR telemetry into analytical spectrometry hardware pipeline.",
        primaryContact: {
          name: "Frederik Møller",
          title: "Director of Digital Health",
          email: "f.moller@kbh-biosystems.dk",
          phone: "+45 33 912 405",
          verified: true,
          avatarColor: "#2ae9c9",
        },
        techStack: ["HL7 / FHIR", "AWS MedTech", "Datadog"],
        matchedPresets: ["all", "high-intent", "hiring"],
        status: "In Cadence",
        lastActive: "Yesterday at 11:20",
        activities: [
          {
            id: "nov-act-3",
            type: "email",
            title: "HL7 Integration Guide Opened (2x)",
            time: "Yesterday at 11:20",
            channel: "Email",
            author: "Automated Cadence",
            status: "Opened",
            description: "Frederik opened the technical whitepaper regarding FHIR API connector speed.",
            badgeColor: "#0284c7",
          },
        ],
      },
      {
        id: "prospect-nov-3",
        businessId: "biz-5",
        company: "Oslo Medical Informatics AS",
        industry: "Enterprise Software",
        location: "Oslo, Norway",
        country: "Norway",
        employees: "60–90",
        website: "oslo-medinfo.no",
        revenue: "$8M–$12M",
        fitScore: 84,
        tier: "middle",
        intentLevel: "High",
        intentTrigger: "Seed Extension Round ($4M) for Norwegian Clinics",
        whyNow: "Piloting clinic management portal; seeking outbound enterprise partnership.",
        primaryContact: {
          name: "Ingrid Bakke",
          title: "Head of Product",
          email: "i.bakke@oslo-medinfo.no",
          phone: "+47 22 840 190",
          verified: true,
          avatarColor: "#42a8a1",
        },
        techStack: ["PostgreSQL", "Next.js", "Stripe"],
        matchedPresets: ["all", "funding"],
        status: "New Match",
        lastActive: "4 days ago",
        activities: [
          {
            id: "nov-act-4",
            type: "signal",
            title: "Seed Extension Round Recorded",
            time: "4 days ago",
            channel: "Nordic Tech Watch",
            author: "Smart Engine AI",
            status: "Logged",
            description: "$4M capital allocation for clinic workflow acceleration.",
            badgeColor: "#c974f4",
          },
        ],
      },
      {
        id: "prospect-nov-4",
        businessId: "biz-5",
        company: "Bergen Healthcare Supplies",
        industry: "Medical Devices",
        location: "Bergen, Norway",
        country: "Norway",
        employees: "35–60",
        website: "bergen-healthsupplies.no",
        revenue: "$4M–$7M",
        fitScore: 61,
        tier: "low",
        intentLevel: "Low",
        intentTrigger: "Annual Catalog Refresh",
        whyNow: "Distributor of generic disposable medical consumables without proprietary software requirements.",
        primaryContact: {
          name: "Einar Nygård",
          title: "Warehouse Operations Lead",
          email: "e.nygard@bergen-healthsupplies.no",
          phone: "+47 55 901 822",
          verified: false,
          avatarColor: "#64748b",
        },
        techStack: ["QuickBooks", "Excel"],
        matchedPresets: ["all"],
        status: "Uncontacted",
        lastActive: "3 weeks ago",
        activities: [
          {
            id: "nov-act-5",
            type: "signal",
            title: "Catalog Refresh Scraped",
            time: "3 weeks ago",
            channel: "Web Scraper",
            author: "Smart Engine AI",
            status: "Low Priority",
            description: "No software stack detected. Low fit score.",
            badgeColor: "#64748b",
          },
        ],
      },
    ],
  },
  {
    id: "biz-10",
    name: "Quantex AI Labs",
    company: "Quantex AI Labs",
    industry: "Cybersecurity",
    country: "Denmark",
    website: "quantex-ai-labs.com",
    owner: "Elena Rostova",
    created: "September 03, 2026",
    avatarColor: "#2ae9c9",
    emailsSent: 44570,
    analytics: {
      totalProspects: 135,
      highTierCount: 64,
      middleTierCount: 48,
      lowTierCount: 23,
      highTierPercent: 47,
      middleTierPercent: 36,
      lowTierPercent: 17,
      avgFitScore: 91,
      buyingSignalsCount: 104,
      meetingsBooked: 29,
      verifiedContactRate: 99.4,
      signalBreakdown: {
        hiring: 48,
        funding: 32,
        expansion: 36,
        tenders: 20,
      },
    },
    prospects: [
      {
        id: "prospect-qtx-1",
        businessId: "biz-10",
        company: "Nordic Bank Financial Tech",
        industry: "Banking & FinTech",
        location: "Copenhagen, Denmark",
        country: "Denmark",
        employees: "1,200–2,000",
        website: "nordicbank-fintech.dk",
        revenue: "$180M–$250M",
        fitScore: 98,
        tier: "high",
        intentLevel: "Very High",
        intentTrigger: "NIS2 Compliance Directive Deadline Compliance Audit",
        whyNow: "Mandated zero-trust infrastructure audit occurring in Q4; sourcing autonomous AI anomaly detection engine.",
        primaryContact: {
          name: "Henrik Christensen",
          title: "Chief Information Security Officer (CISO)",
          email: "h.christensen@nordicbank.dk",
          phone: "+45 33 400 918",
          verified: true,
          avatarColor: "#2ae9c9",
        },
        techStack: ["Splunk", "CrowdStrike", "Kubernetes", "AWS GovCloud"],
        matchedPresets: ["all", "high-intent", "tenders"],
        status: "Engaged",
        lastActive: "Today at 10:15",
        activities: [
          {
            id: "qtx-act-1",
            type: "meeting",
            title: "Executive Security Council Pitch",
            time: "Today at 10:15",
            channel: "In-person",
            author: "Elena Rostova",
            status: "Completed",
            description: "Presented Quantex autonomous SIEM enrichment at Copenhagen HQ. RFP documentation requested.",
            badgeColor: "#7c3aed",
          },
          {
            id: "qtx-act-2",
            type: "email",
            title: "NDA & Compliance Packet Executed",
            time: "Yesterday at 17:00",
            channel: "DocuSign",
            author: "Henrik Christensen",
            status: "Signed",
            description: "Mutual NDA executed for production cluster telemetry testing.",
            badgeColor: "#059669",
          },
        ],
      },
      {
        id: "prospect-qtx-2",
        businessId: "biz-10",
        company: "Baltic Cloud Infrastructure SIA",
        industry: "Cloud & Datacenter",
        location: "Riga, Latvia",
        country: "Latvia",
        employees: "220–380",
        website: "balticcloud.eu",
        revenue: "$25M–$40M",
        fitScore: 93,
        tier: "high",
        intentLevel: "High",
        intentTrigger: "Announced 10MW Green Datacenter Facility",
        whyNow: "Expanding sovereign European cloud footprint with built-in AI edge protection.",
        primaryContact: {
          name: "Kaspars Liepins",
          title: "VP Cloud Engineering",
          email: "k.liepins@balticcloud.eu",
          phone: "+371 67 201 449",
          verified: true,
          avatarColor: "#c974f4",
        },
        techStack: ["OpenStack", "Terraform", "Palo Alto Networks"],
        matchedPresets: ["all", "high-intent", "expansion"],
        status: "In Cadence",
        lastActive: "Yesterday at 14:00",
        activities: [
          {
            id: "qtx-act-3",
            type: "email",
            title: "Outreach Touchpoint #2 Clicked",
            time: "Yesterday at 14:00",
            channel: "Email",
            author: "Elena Rostova",
            status: "Clicked",
            description: "Prospect clicked 'View Datacenter Security Architecture Whitepaper'.",
            badgeColor: "#0284c7",
          },
        ],
      },
      {
        id: "prospect-qtx-3",
        businessId: "biz-10",
        company: "Vistula Telecommunications SA",
        industry: "Telecommunications",
        location: "Warsaw, Poland",
        country: "Poland",
        employees: "500–850",
        website: "vistula-telecom.pl",
        revenue: "$70M–$100M",
        fitScore: 81,
        tier: "middle",
        intentLevel: "Medium",
        intentTrigger: "Recruiting 8 Network Security Analysts",
        whyNow: "Expanding 5G core network monitoring team.",
        primaryContact: {
          name: "Marek Kowalski",
          title: "Lead Network Operations Manager",
          email: "m.kowalski@vistula-telecom.pl",
          phone: "+48 22 819 302",
          verified: true,
          avatarColor: "#dc9c56",
        },
        techStack: ["Cisco", "Nokia 5G", "Fortinet"],
        matchedPresets: ["all", "hiring"],
        status: "New Match",
        lastActive: "3 days ago",
        activities: [
          {
            id: "qtx-act-4",
            type: "signal",
            title: "5G Core Engineering Surge",
            time: "3 days ago",
            channel: "Job Boards",
            author: "Smart Engine AI",
            status: "Logged",
            description: "Surge in network security roles detected across Warsaw operations.",
            badgeColor: "#d97706",
          },
        ],
      },
      {
        id: "prospect-qtx-4",
        businessId: "biz-10",
        company: "Vilnius Fiber Connectivity UAB",
        industry: "Telecommunications",
        location: "Vilnius, Lithuania",
        country: "Lithuania",
        employees: "40–70",
        website: "vilnius-fiber.lt",
        revenue: "$3M–$6M",
        fitScore: 65,
        tier: "low",
        intentLevel: "Low",
        intentTrigger: "Municipal Fiber Cable Expansion Tender",
        whyNow: "Local physical civil engineering contractor laying subterranean optical fiber.",
        primaryContact: {
          name: "Jonas Petrauskas",
          title: "Field Engineering Lead",
          email: "j.petrauskas@vilnius-fiber.lt",
          phone: "+370 5 210 994",
          verified: false,
          avatarColor: "#64748b",
        },
        techStack: ["AutoCAD", "GIS Mapping"],
        matchedPresets: ["all"],
        status: "Uncontacted",
        lastActive: "2 weeks ago",
        activities: [
          {
            id: "qtx-act-5",
            type: "signal",
            title: "Municipal Trenching Tender Scraped",
            time: "2 weeks ago",
            channel: "Public Tenders",
            author: "Smart Engine AI",
            status: "Low Priority",
            description: "Physical trenching project with minimal cyber requirement.",
            badgeColor: "#64748b",
          },
        ],
      },
    ],
  },
];

// Flat export of all prospects for backward compatibility
export const SMART_LEADS_DATA: SmartLead[] = ONBOARDED_BUSINESSES_DATA.flatMap((b) => b.prospects);
